# Generated by Django 5.1.2 on 2024-12-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories_burned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
